version: '3'
services:
  movies:
    image: swaroop2002/moviesrepopayttm:latest

    ports:
      - "80:80"
    deploy:
      replicas: 3

  train:
    image: swaroop2002/trainrepopayttm:latest

    ports:
      - "81:80"
    deploy:
      replicas: 3

  dth:
    image: swaroop2002/dthrepopayttm:latest

    ports:
      - "82:80"
    deploy:
      replicas: 3

  recharge:
    image: swaroop2002/rechargerepopayttm:latest

    ports:
      - "83:80"
    deploy:
      replicas: 3
